name: Build and Commit Bubble Room Dev

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        env:
          npm_config_ignore_optional: true

      - name: Run build
        run: npm run build

      - name: Rename output
        run: mv dist/lovelace-bubble-room.js bubble-room-dev.js
      - name: Check if GH_PAT is available
        run: echo "GH_PAT is ${{ secrets.GH_PAT }}"

      - name: Commit to dev branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git fetch origin
          git switch dev
          git pull origin dev || true
          git add bubble-room-dev.js
          git commit -m "Auto-commit dev build from workflow" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/mon3y78/Lovelace-Bubble-room.git
          git remote -v
          git push origin dev
