name: Build and Commit Bubble Room Dev

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        env:
          npm_config_ignore_optional: true

      - name: Run Rollup build
        run: npm run build

      - name: Commit final JS build to dev branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add lovelace-bubble-room.js
          git commit -m "Auto-build from GitHub Action" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/mon3y78/Lovelace-Bubble-room.git dev
