name: Build and Commit Bubble Room Dev

on:
  workflow_dispatch:

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (dev branch)
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        env:
          npm_config_ignore_optional: true

      - name: Run build
        run: npm run build

      - name: Rename output
        run: mv dist/lovelace-bubble-room.js bubble-room-dev.js

      - name: Commit build to dev-build branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git switch --force-create dev-build || git switch dev-build
          cp bubble-room-dev.js ./bubble-room-dev.js
          git add bubble-room-dev.js
          git commit -m "Auto-commit dev build from workflow" || echo "Nothing to commit"
          git push origin dev-build
