name: Build and Commit Bubble Room

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and ensure JSON plugin
        run: |
          npm install --save-dev @rollup/plugin-json
          npm install

      - name: Build lovelace-bubble-room bundle
        run: npm run build

      # —————— DEBUG: controlla l’head del bundle
      - name: Dump head of built bundle
        run: head -n 30 lovelace-bubble-room.js

      # —————— DEBUG: cerca import “path”
      - name: Check for stray “path” import
        run: grep -n "from ['\"]path['\"]" lovelace-bubble-room.js || echo "✅ no path import found"

      - name: Commit generated files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add package.json package-lock.json lovelace-bubble-room.js
          git commit -m "Auto-build: update bundle and dependencies" || echo "No changes to commit"

      - name: Push changes back to repo
        run: git push origin HEAD:${{ github.ref_name }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bubble-room-bundle
          path: lovelace-bubble-room.js
