name: Build Bubble Room Dev

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch da cui fare build'
        default: 'dev'


jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}


      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        env:
          npm_config_ignore_optional: true




      - name: Run build
        run: npm run build

      - name: Rename output to dev version
        run: mv dist/lovelace-bubble-room.js dist/bubble-room-dev.js

      - name: Upload dev build
        uses: actions/upload-artifact@v4
        with:
          name: bubble-room-dev
          path: dist/bubble-room-dev.js
