name: Delete pre-releases v3.1.x

on:
  workflow_dispatch:

jobs:
  delete-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y curl jq
          curl -fsSL -o gh.deb https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb
          sudo dpkg -i gh.deb

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${GH_TOKEN}" | gh auth login --with-token

      - name: Delete pre-releases v3.1.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Cercando pre-release con tag v3.1.x..."

          gh api repos/${{ github.repository }}/releases --paginate \
          | jq -r '.[] | select(.tag_name | test("^v3\\.1\\.[0-9]+$")) | select(.prerelease == true) | .tag_name' \
          | while read TAG; do
              echo "🗑️ Eliminando pre-release e tag: $TAG"
              gh release delete "$TAG" --yes || echo "⚠️ Release non trovata"
              git push origin --delete "$TAG" || echo "⚠️ Tag Git non trovato"
            done

          echo "✅ Completato."