name: Delete matching pre-releases

on:
  workflow_dispatch:
    inputs:
      base_version:
        description: 'Versione base (es. 3.1)'
        required: true
        default: '3.1'

jobs:
  delete-matching-prereleases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y curl jq
          curl -fsSL -o gh.deb https://github.com/cli/cli/releases/download/v2.45.0/gh_2.45.0_linux_amd64.deb
          sudo dpkg -i gh.deb

      - name: Delete matching pre-releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BASE="${{ github.event.inputs.base_version }}"
