name: "Validate with HACS"
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install HACS validation tool
        run: |
          python -m pip install --upgrade pip
          pip install hacs-cli

      - name: Run validation
        run: hacs validate